/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xx.h"

int main(void)
{
	// Enable clock for GPIOA
	GPIOA_CLK_EN();

	// Set PA0 as output
	GPIOA->MODER |=(1<< 0);


	GPIOA->ODR |= (1<<0);
	while(1)
	{


		for(uint32_t i=0;i<10000;i++)
			;
	}




}







